name: flutter_locale_master
description: "Advanced Flutter localization with automatic RTL/LTR switching, reactive UI updates, asset-based translations, pluralization, and custom widgets."
version: 1.0.4
homepage: https://github.com/khedrmahmoud/Flutter-Locale-Master
repository: https://github.com/khedrmahmoud/Flutter-Locale-Master
issue_tracker: https://github.com/khedrmahmoud/Flutter-Locale-Master/issues
documentation: https://github.com/khedrmahmoud/Flutter-Locale-Master#readme

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15

topics:
  - localization
  - internationalization
  - i18n
  - rtl
  - flutter

# The following section is specific to Flutter packages.
flutter:
