name: flutter_locale_master
description: "Advanced Flutter localization package with automatic RTL/LTR text direction switching, reactive UI updates, asset-based translations, pluralization, parameter interpolation, namespace support, and custom widgets. Production-ready with comprehensive testing and clean architecture."
version: 1.0.0
homepage: https://github.com/khedr07/flutter_locale_master
repository: https://github.com/khedr07/flutter_locale_master
issue_tracker: https://github.com/khedr07/flutter_locale_master/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15

topics:
  - localization
  - internationalization
  - i18n
  - rtl
  - ltr
  - translation
  - flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
